name: Jekyll site CI

on:
  push:
    branches: [ "feat-set-up-CICD" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: ${{  matrix.platform  }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    
  test:
    
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: ${{  matrix.platform  }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Test through simple print
      run: echo "Hello!"
